apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-code-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-code-challenge
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-code-challenge
    spec:
      containers:
      - name: gke-code-challenge
        image: us-east1-docker.pkg.dev/codechallenge-349907/char/code-challenge-image:latest
        env:
        - name: URI
          valueFrom:
            secreteKeyRef:
              name: dbconnection
              key: uri
              optional: false
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m